import type { AppLanguage } from '@/stores/use-app-store'

export const uiCopy = {
  en: {
    settings: { title: 'Settings', description: 'Configure Eva to your preferences', general: 'General', models: 'Models', cost: 'Cost center', agents: 'Agents', automation: 'Automation', plugins: 'Plugins', qq: 'QQ Remote', about: 'About', language: 'Interface language', languageDescription: 'Changes apply immediately and are remembered for future launches.', workspace: 'Workspace Path', workspacePlaceholder: 'Select a folder or enter its full path', browse: 'Browse', workspaceDescription: 'Used as a fallback for older conversations. New conversations use their selected project, and file access is configured in each conversation input bar.', costDescription: 'Review usage, token volume, cache hits, supplier and model costs, then maintain the local model rate cards used for estimates.', openCost: 'Open cost center' },
    cost: { title: 'Cost center', subtitle: 'Usage, pricing estimates, and cache efficiency across model connections.', back: 'Back to chat', refresh: 'Refresh', timePeriod: 'Time period', aggregation: 'Aggregation', supplier: 'Supplier', allSuppliers: 'All suppliers', last7: 'Last 7 days', last30: 'Last 30 days', last90: 'Last 90 days', allTime: 'All time', daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly', estimatedCost: 'Estimated cost', modelCalls: 'Model calls', tokenVolume: 'Token volume', cacheHitRate: 'Cache hit rate', allRecordsPriced: 'All records priced', recordsPriced: 'records priced', usageRecords: 'usage records', input: 'Input', output: 'Output', cachedInputTokens: 'cached input tokens', costTrend: 'Estimated cost trend', costTrendDescription: 'Cost is shown only where a rate card or stored estimate is available.', supplierAllocation: 'Supplier allocation', noUsage: 'No usage records yet.', modelUsage: 'Model usage', modelUsageDescription: 'Grouped by supplier and model for the selected time period.', cost: 'Cost', calls: 'Calls', cacheHit: 'Cache hit', noMatchingUsage: 'No usage records match these filters.', rateCards: 'Model rate cards', rateCardsDescription: 'Local reference prices in CNY per million tokens. These determine estimates for records without a provider-reported cost.', addRate: 'Add rate', saveRates: 'Save rates', saving: 'Saving...', cachedInput: 'Cached input / M', inputPerMillion: 'Input / M', outputPerMillion: 'Output / M', noRateCards: 'Add a rate card to estimate models that do not report cost.', modelId: 'Model ID or *', supplierId: 'Supplier ID' },
  },
  zh: {
    settings: { title: '设置', description: '配置 Eva 的使用偏好', general: '通用', models: '模型', cost: '成本中心', agents: '智能体', automation: '自动化', plugins: '插件', qq: 'QQ 远程控制', about: '关于', language: '界面语言', languageDescription: '切换后立即生效，并会在下次启动时保持。', workspace: '工作区路径', workspacePlaceholder: '选择文件夹或输入完整路径', browse: '浏览', workspaceDescription: '用于兼容较早的对话。新对话使用所选项目，文件访问权限在每个对话的输入栏中配置。', costDescription: '查看用量、Token 数、缓存命中率以及供应商和模型成本，并维护用于估算的本地模型价格卡。', openCost: '打开成本中心' },
    cost: { title: '成本中心', subtitle: '查看各模型连接的用量、价格估算和缓存效率。', back: '返回聊天', refresh: '刷新', timePeriod: '时间范围', aggregation: '统计粒度', supplier: '供应商', allSuppliers: '全部供应商', last7: '最近 7 天', last30: '最近 30 天', last90: '最近 90 天', allTime: '全部时间', daily: '按日', weekly: '按周', monthly: '按月', estimatedCost: '预估成本', modelCalls: '模型调用', tokenVolume: 'Token 用量', cacheHitRate: '缓存命中率', allRecordsPriced: '全部记录已计价', recordsPriced: '条记录已计价', usageRecords: '条用量记录', input: '输入', output: '输出', cachedInputTokens: '缓存输入 Token', costTrend: '预估成本趋势', costTrendDescription: '仅在存在价格卡或已存储估算时显示成本。', supplierAllocation: '供应商分布', noUsage: '暂无用量记录。', modelUsage: '模型用量', modelUsageDescription: '按选定时间范围内的供应商和模型分组。', cost: '成本', calls: '调用次数', cacheHit: '缓存命中', noMatchingUsage: '没有符合当前筛选条件的用量记录。', rateCards: '模型价格卡', rateCardsDescription: '以每百万 Token 的人民币本地参考价计算。它们用于估算供应商未返回成本的记录。', addRate: '添加价格', saveRates: '保存价格', saving: '保存中...', cachedInput: '缓存输入 / M', inputPerMillion: '输入 / M', outputPerMillion: '输出 / M', noRateCards: '添加价格卡以估算未返回成本的模型。', modelId: '模型 ID 或 *', supplierId: '供应商 ID' },
  },
  ja: {
    settings: { title: '設定', description: 'Eva の環境設定', general: '一般', models: 'モデル', cost: 'コストセンター', agents: 'エージェント', automation: '自動化', plugins: 'プラグイン', qq: 'QQ リモート', about: '情報', language: '表示言語', languageDescription: '変更はすぐに反映され、次回の起動後も保持されます。', workspace: 'ワークスペースのパス', workspacePlaceholder: 'フォルダーを選択するか、完全なパスを入力', browse: '参照', workspaceDescription: '以前の会話のフォールバックとして使用します。新しい会話では選択したプロジェクトを使用し、ファイルアクセスは各会話の入力欄で設定します。', costDescription: '使用量、トークン数、キャッシュヒット率、プロバイダー・モデル別コストを確認し、推定用のローカル料金表を管理します。', openCost: 'コストセンターを開く' },
    cost: { title: 'コストセンター', subtitle: 'モデル接続ごとの使用量、料金推定、キャッシュ効率を確認します。', back: 'チャットに戻る', refresh: '更新', timePeriod: '期間', aggregation: '集計単位', supplier: 'プロバイダー', allSuppliers: 'すべてのプロバイダー', last7: '過去 7 日間', last30: '過去 30 日間', last90: '過去 90 日間', allTime: '全期間', daily: '日別', weekly: '週別', monthly: '月別', estimatedCost: '推定コスト', modelCalls: 'モデル呼び出し', tokenVolume: 'トークン使用量', cacheHitRate: 'キャッシュヒット率', allRecordsPriced: 'すべての記録を計上済み', recordsPriced: '件を計上済み', usageRecords: '件の使用量記録', input: '入力', output: '出力', cachedInputTokens: 'キャッシュ入力トークン', costTrend: '推定コストの推移', costTrendDescription: '料金表または保存済みの推定値がある場合にのみコストを表示します。', supplierAllocation: 'プロバイダー別内訳', noUsage: '使用量の記録はまだありません。', modelUsage: 'モデル使用量', modelUsageDescription: '選択した期間のプロバイダーとモデルごとに集計します。', cost: 'コスト', calls: '呼び出し', cacheHit: 'キャッシュヒット', noMatchingUsage: 'この条件に一致する使用量記録はありません。', rateCards: 'モデル料金表', rateCardsDescription: '100 万トークンあたりの人民元によるローカル参照価格です。プロバイダーからコストが返らない記録の推定に使用します。', addRate: '料金を追加', saveRates: '料金を保存', saving: '保存中...', cachedInput: 'キャッシュ入力 / M', inputPerMillion: '入力 / M', outputPerMillion: '出力 / M', noRateCards: 'コストを返さないモデルを推定するため、料金表を追加してください。', modelId: 'モデル ID または *', supplierId: 'プロバイダー ID' },
  },
} satisfies Record<AppLanguage, { settings: Record<string, string>; cost: Record<string, string> }>
