import type { AppLanguage } from '@/stores/use-app-store'

export const uiCopy = {
  en: {
    agents: {
      workspace: 'Agent workspace', heading: 'Specialists ready for each kind of work', description: 'Review responsibilities at a glance, then configure models and tools only when needed.', search: 'Search agents', create: 'Create agent', specialist: 'Create specialist', builtIn: 'Built-in agents', custom: 'Custom agents', builtInBadge: 'Built-in', customBadge: 'Custom', primaryChatAgent: 'Main chat agent', primaryChatAgentBadge: 'Main chat', setPrimaryChatAgent: 'Set as main chat agent', managePrimaryChatAgent: 'Manage', models: 'models', tools: 'tools', noDescription: 'No description provided.', noMatch: 'No agents match this search.', modelAccess: 'Model access', modelDescription: 'Connections available for delegated work.', toolAccess: 'Tool access', toolDescription: 'Only the capabilities needed for this responsibility.', configure: 'Configure', noTools: 'No tools assigned.', systemInstructions: 'System instructions', builtInInstructions: 'Built-in instructions are maintained by Eva. Model and tool access remain configurable.', customInstructions: "Instructions defining this specialist's role and working style.", back: 'Back to', edit: 'Edit agent', delete: 'Delete agent', deleteQuestion: 'Delete {name}?', deleteDescription: 'This removes the custom agent and its saved configuration. Existing conversations will remain available.', keep: 'Keep agent', saveTools: 'Save tool access', saveModels: 'Save model access', cancel: 'Cancel', save: 'Save', temperature: 'Temperature', iterationLimit: 'Iteration limit', assignedTools: 'Assigned tools', noCandidates: 'No model connection configured.', name: 'Name', role: 'Role', descriptionLabel: 'Description', systemPrompt: 'System prompt', provider: 'Provider', model: 'Model', nameRequired: 'Name is required', nameHint: 'Roles are reusable templates. Give each agent an individual name.', codingAssistant: 'Coding Assistant', codeReviewer: 'Code Reviewer', researchAnalyst: 'Research Analyst', teamLeader: 'Team Leader', coder: 'Coder', reviewer: 'Reviewer', researcher: 'Researcher', leader: 'Leader', tester: 'Tester', customRole: 'Custom'
    },
    automation: { title: 'Internal capabilities', description: 'Capabilities available to the agent as internal tools. They stay within the current conversation and are injected into system context only when enabled.', enabled: 'Enabled', off: 'Off', flow: 'Flow', context: 'System context', services: 'Skills and services', invoke: 'Agent may invoke', maxSteps: 'Maximum steps', timeout: 'Timeout (minutes)' },
    settings: { title: 'Settings', description: 'Configure Eva to your preferences', general: 'General', models: 'Models', cost: 'Cost center', agents: 'Agents', automation: 'Automation', plugins: 'Plugins', qq: 'QQ Remote', about: 'About', language: 'Interface language', languageDescription: 'Changes apply immediately and are remembered for future launches.', workspace: 'Workspace Path', workspacePlaceholder: 'Select a folder or enter its full path', browse: 'Browse', workspaceDescription: 'Used as a fallback for older conversations. New conversations use their selected project, and file access is configured in each conversation input bar.', costDescription: 'Review usage, token volume, cache hits, supplier and model costs, then maintain the local model rate cards used for estimates.', openCost: 'Open cost center' },
    cost: { title: 'Cost center', subtitle: 'Usage, pricing estimates, and cache efficiency across model connections.', back: 'Back to chat', refresh: 'Refresh', timePeriod: 'Time period', aggregation: 'Aggregation', supplier: 'Supplier', allSuppliers: 'All suppliers', last7: 'Last 7 days', last30: 'Last 30 days', last90: 'Last 90 days', allTime: 'All time', daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly', estimatedCost: 'Estimated cost', modelCalls: 'Model calls', tokenVolume: 'Token volume', cacheHitRate: 'Cache hit rate', allRecordsPriced: 'All records priced', recordsPriced: 'records priced', usageRecords: 'usage records', input: 'Input', output: 'Output', cachedInputTokens: 'cached input tokens', costTrend: 'Estimated cost trend', costTrendDescription: 'Cost is shown only where a rate card or stored estimate is available.', supplierAllocation: 'Supplier allocation', noUsage: 'No usage records yet.', modelUsage: 'Model usage', modelUsageDescription: 'Grouped by supplier and model for the selected time period.', cost: 'Cost', calls: 'Calls', cacheHit: 'Cache hit', noMatchingUsage: 'No usage records match these filters.', rateCards: 'Model rate cards', rateCardsDescription: 'Local reference prices in CNY per million tokens. These determine estimates for records without a provider-reported cost.', addRate: 'Add rate', saveRates: 'Save rates', saving: 'Saving...', cachedInput: 'Cached input / M', inputPerMillion: 'Input / M', outputPerMillion: 'Output / M', noRateCards: 'Add a rate card to estimate models that do not report cost.', modelId: 'Model ID or *', supplierId: 'Supplier ID' },
  },
  zh: {
    agents: {
      workspace: '智能体工作区', heading: '为不同类型的任务准备专长智能体', description: '先快速了解职责，需要时再配置模型和工具。', search: '搜索智能体', create: '创建智能体', specialist: '创建专长智能体', builtIn: '内置智能体', custom: '自定义智能体', builtInBadge: '内置', customBadge: '自定义', primaryChatAgent: '主对话智能体', primaryChatAgentBadge: '主对话', setPrimaryChatAgent: '设为主对话智能体', managePrimaryChatAgent: '管理', models: '个模型', tools: '个工具', noDescription: '暂无描述。', noMatch: '没有匹配的智能体。', modelAccess: '模型访问', modelDescription: '可用于委派任务的连接。', toolAccess: '工具访问', toolDescription: '仅分配完成职责所需的能力。', configure: '配置', noTools: '未分配工具。', systemInstructions: '系统指令', builtInInstructions: '内置指令由 Eva 维护，模型和工具访问仍可配置。', customInstructions: '定义该专长智能体职责和工作方式的指令。', back: '返回', edit: '编辑智能体', delete: '删除智能体', deleteQuestion: '删除{name}？', deleteDescription: '这会删除自定义智能体及其保存的配置，已有对话不会受到影响。', keep: '保留智能体', saveTools: '保存工具访问', saveModels: '保存模型访问', cancel: '取消', save: '保存', temperature: '温度', iterationLimit: '迭代上限', assignedTools: '已分配工具', noCandidates: '未配置模型连接。', name: '名称', role: '角色', descriptionLabel: '描述', systemPrompt: '系统提示词', provider: '供应商', model: '模型', nameRequired: '请输入名称', nameHint: '角色可复用，请为每个智能体设置独立名称。', codingAssistant: '编程助手', codeReviewer: '代码审查员', researchAnalyst: '研究分析师', teamLeader: '团队负责人', coder: '开发者', reviewer: '审查员', researcher: '研究员', leader: '负责人', tester: '测试员', customRole: '自定义'
    },
    automation: { title: '内部能力', description: '智能体可使用的内部工具。启用后，它们只在当前对话中生效，并注入系统上下文。', enabled: '已启用', off: '关闭', flow: '流程', context: '系统上下文', services: '技能与服务', invoke: '允许智能体调用', maxSteps: '最大步骤数', timeout: '超时时间（分钟）' },
    settings: { title: '设置', description: '配置 Eva 的使用偏好', general: '通用', models: '模型', cost: '成本中心', agents: '智能体', automation: '自动化', plugins: '插件', qq: 'QQ 远程控制', about: '关于', language: '界面语言', languageDescription: '切换后立即生效，并会在下次启动时保持。', workspace: '工作区路径', workspacePlaceholder: '选择文件夹或输入完整路径', browse: '浏览', workspaceDescription: '用于兼容较早的对话。新对话使用所选项目，文件访问权限在每个对话的输入栏中配置。', costDescription: '查看用量、Token 数、缓存命中率以及供应商和模型成本，并维护用于估算的本地模型价格卡。', openCost: '打开成本中心' },
    cost: { title: '成本中心', subtitle: '查看各模型连接的用量、价格估算和缓存效率。', back: '返回聊天', refresh: '刷新', timePeriod: '时间范围', aggregation: '统计粒度', supplier: '供应商', allSuppliers: '全部供应商', last7: '最近 7 天', last30: '最近 30 天', last90: '最近 90 天', allTime: '全部时间', daily: '按日', weekly: '按周', monthly: '按月', estimatedCost: '预估成本', modelCalls: '模型调用', tokenVolume: 'Token 用量', cacheHitRate: '缓存命中率', allRecordsPriced: '全部记录已计价', recordsPriced: '条记录已计价', usageRecords: '条用量记录', input: '输入', output: '输出', cachedInputTokens: '缓存输入 Token', costTrend: '预估成本趋势', costTrendDescription: '仅在存在价格卡或已存储估算时显示成本。', supplierAllocation: '供应商分布', noUsage: '暂无用量记录。', modelUsage: '模型用量', modelUsageDescription: '按选定时间范围内的供应商和模型分组。', cost: '成本', calls: '调用次数', cacheHit: '缓存命中', noMatchingUsage: '没有符合当前筛选条件的用量记录。', rateCards: '模型价格卡', rateCardsDescription: '以每百万 Token 的人民币本地参考价计算。它们用于估算供应商未返回成本的记录。', addRate: '添加价格', saveRates: '保存价格', saving: '保存中...', cachedInput: '缓存输入 / M', inputPerMillion: '输入 / M', outputPerMillion: '输出 / M', noRateCards: '添加价格卡以估算未返回成本的模型。', modelId: '模型 ID 或 *', supplierId: '供应商 ID' },
  },
  ja: {
    agents: {
      workspace: 'エージェントワークスペース', heading: '役割ごとのスペシャリスト', description: '役割を一覧で確認し、必要なときだけモデルとツールを設定します。', search: 'エージェントを検索', create: 'エージェントを作成', specialist: 'スペシャリストを作成', builtIn: '組み込みエージェント', custom: 'カスタムエージェント', builtInBadge: '組み込み', customBadge: 'カスタム', primaryChatAgent: 'メインチャットエージェント', primaryChatAgentBadge: 'メインチャット', setPrimaryChatAgent: 'メインチャットに設定', managePrimaryChatAgent: '管理', models: 'モデル', tools: 'ツール', noDescription: '説明はありません。', noMatch: '一致するエージェントはありません。', modelAccess: 'モデルアクセス', modelDescription: '委任作業で利用できる接続。', toolAccess: 'ツールアクセス', toolDescription: '役割に必要な機能だけを割り当てます。', configure: '設定', noTools: 'ツールは未割り当てです。', systemInstructions: 'システム指示', builtInInstructions: '組み込み指示は Eva が管理します。モデルとツールは設定できます。', customInstructions: 'スペシャリストの役割と作業方法を定義する指示。', back: '戻る', edit: 'エージェントを編集', delete: 'エージェントを削除', deleteQuestion: '{name}を削除しますか？', deleteDescription: 'カスタムエージェントと保存済み設定を削除します。既存の会話は残ります。', keep: '保持', saveTools: 'ツールアクセスを保存', saveModels: 'モデルアクセスを保存', cancel: 'キャンセル', save: '保存', temperature: '温度', iterationLimit: '反復上限', assignedTools: '割り当て済みツール', noCandidates: 'モデル接続が設定されていません。', name: '名前', role: '役割', descriptionLabel: '説明', systemPrompt: 'システムプロンプト', provider: 'プロバイダー', model: 'モデル', nameRequired: '名前は必須です', nameHint: '役割は再利用できます。各エージェントに固有の名前を付けてください。', codingAssistant: 'コーディングアシスタント', codeReviewer: 'コードレビュアー', researchAnalyst: 'リサーチアナリスト', teamLeader: 'チームリーダー', coder: 'コーダー', reviewer: 'レビューアー', researcher: 'リサーチャー', leader: 'リーダー', tester: 'テスター', customRole: 'カスタム'
    },
    automation: { title: '内部機能', description: 'エージェントが内部ツールとして利用できる機能です。有効にすると現在の会話だけで使用され、システムコンテキストに追加されます。', enabled: '有効', off: 'オフ', flow: 'フロー', context: 'システムコンテキスト', services: 'スキルとサービス', invoke: 'エージェントによる呼び出し', maxSteps: '最大ステップ数', timeout: 'タイムアウト（分）' },
    settings: { title: '設定', description: 'Eva の環境設定', general: '一般', models: 'モデル', cost: 'コストセンター', agents: 'エージェント', automation: '自動化', plugins: 'プラグイン', qq: 'QQ リモート', about: '情報', language: '表示言語', languageDescription: '変更はすぐに反映され、次回の起動後も保持されます。', workspace: 'ワークスペースのパス', workspacePlaceholder: 'フォルダーを選択するか、完全なパスを入力', browse: '参照', workspaceDescription: '以前の会話のフォールバックとして使用します。新しい会話では選択したプロジェクトを使用し、ファイルアクセスは各会話の入力欄で設定します。', costDescription: '使用量、トークン数、キャッシュヒット率、プロバイダー・モデル別コストを確認し、推定用のローカル料金表を管理します。', openCost: 'コストセンターを開く' },
    cost: { title: 'コストセンター', subtitle: 'モデル接続ごとの使用量、料金推定、キャッシュ効率を確認します。', back: 'チャットに戻る', refresh: '更新', timePeriod: '期間', aggregation: '集計単位', supplier: 'プロバイダー', allSuppliers: 'すべてのプロバイダー', last7: '過去 7 日間', last30: '過去 30 日間', last90: '過去 90 日間', allTime: '全期間', daily: '日別', weekly: '週別', monthly: '月別', estimatedCost: '推定コスト', modelCalls: 'モデル呼び出し', tokenVolume: 'トークン使用量', cacheHitRate: 'キャッシュヒット率', allRecordsPriced: 'すべての記録を計上済み', recordsPriced: '件を計上済み', usageRecords: '件の使用量記録', input: '入力', output: '出力', cachedInputTokens: 'キャッシュ入力トークン', costTrend: '推定コストの推移', costTrendDescription: '料金表または保存済みの推定値がある場合にのみコストを表示します。', supplierAllocation: 'プロバイダー別内訳', noUsage: '使用量の記録はまだありません。', modelUsage: 'モデル使用量', modelUsageDescription: '選択した期間のプロバイダーとモデルごとに集計します。', cost: 'コスト', calls: '呼び出し', cacheHit: 'キャッシュヒット', noMatchingUsage: 'この条件に一致する使用量記録はありません。', rateCards: 'モデル料金表', rateCardsDescription: '100 万トークンあたりの人民元によるローカル参照価格です。プロバイダーからコストが返らない記録の推定に使用します。', addRate: '料金を追加', saveRates: '料金を保存', saving: '保存中...', cachedInput: 'キャッシュ入力 / M', inputPerMillion: '入力 / M', outputPerMillion: '出力 / M', noRateCards: 'コストを返さないモデルを推定するため、料金表を追加してください。', modelId: 'モデル ID または *', supplierId: 'プロバイダー ID' },
  },
} satisfies Record<AppLanguage, { settings: Record<string, string>; cost: Record<string, string>; agents: Record<string, string>; automation: Record<string, string> }>
