/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Mirrors the JS `SandboxConfig` shape. */
export interface JsSandboxConfig {
  level?: string
  allowNetwork?: boolean
  extraAllowedPaths?: Array<string>
  extraCommandPatterns?: Array<string>
}
/** Mirrors the JS `ProfileInputs` shape. */
export interface JsProfileInputs {
  workspacePath: string
  extraAllowedPaths?: Array<string>
  allowNetwork?: boolean
}
/** Mirrors the JS `SandboxContext` shape (only the fields the FFI surface needs). */
export interface JsSandboxContext {
  workspacePath: string
  fileAccessGrants?: Array<JsFileAccessGrant>
  extraAllowedPaths?: Array<string>
  allowNetwork?: boolean
  level: string
}
/** Mirrors the JS `FileAccessGrant` shape. */
export interface JsFileAccessGrant {
  path: string
  access: string
}
/**
 * Resolve the effective sandbox policy.
 * Mirrors `resolveSandboxPolicy` in policy.ts.
 */
export declare function resolveSandboxPolicyJs(approvalPolicy: string, sandbox: JsSandboxConfig, mode: string): string
/** Build both OS-specific profiles in one call. */
export declare function buildProfiles(inputs: JsProfileInputs): string
/** Evaluate a filesystem path.  Mirrors `pathDecision` in darwin.ts. */
export declare function pathDecisionJs(targetPath: string, operation: string, context: JsSandboxContext, backend: string): string
/** Evaluate a shell command.  Mirrors `defaultCommandDecision` in darwin.ts. */
export declare function defaultCommandDecisionJs(commandLine: string, context: JsSandboxContext, backend: string): string
/** Probe Darwin `sandbox-exec`.  Returns a JSON `ProbeResult`. */
export declare function probeDarwin(): Promise<string>
/** Probe Linux `bwrap`.  Returns a JSON `ProbeResult`. */
export declare function probeLinux(): Promise<string>
/** Probe noop.  Always returns `{ available: true, error: null }`. */
export declare function probeNoop(): string
/** Wrap argv for Darwin `sandbox-exec`.  Returns a JSON `WrappedCommand`. */
export declare function wrapDarwin(command: string, args: Array<string>, context: JsSandboxContext): string
/** Wrap argv for Linux `bwrap`.  Returns a JSON `WrappedCommand`. */
export declare function wrapLinux(command: string, args: Array<string>, context: JsSandboxContext): string
