import type { ToolCall } from './conversation'
import type { AgentModelPreference } from './agent'

export type TaskStatus = 'pending' | 'in_progress' | 'completed' | 'failed' | 'cancelled'

export interface TaskPlan {
  id: string
  goal: string
  subtasks: SubTask[]
  createdAt: number
  status: TaskStatus
  /** Specialists generated by the leader for this plan only. */
  dynamicAgents?: DynamicAgentProfile[]
}

export interface DynamicAgentProfile {
  id: string
  name: string
  description: string
  systemPrompt: string
  tools: string[]
  modelPreference?: AgentModelPreference
}

export interface SubTask {
  id: string
  planId: string
  title: string
  description: string
  status: TaskStatus
  assignedAgentId?: string
  assignedAgentName?: string
  /** Role selected by the leader during planning. */
  assignedRole?: 'researcher' | 'coder' | 'reviewer' | 'tester'
  /** Exact connection chosen for this execution, after model matching. */
  assignedProviderId?: string
  assignedModel?: string
  /** References a task-scoped member from TaskPlan.dynamicAgents. */
  assignedAgentProfileId?: string
  isDynamicAgent?: boolean
  /** Separate persisted context for this agent's work on the subtask. */
  agentConversationId?: string
  /** One-based execution attempt number. Failed tasks are retried once. */
  attempt?: number
  dependencies: string[]
  result?: string
  /** Tool activity retained for project-level task artifacts. */
  toolCalls?: ToolCall[]
  startedAt?: number
  completedAt?: number
}

export interface TeamEvent {
  type: 'plan_created' | 'task_created' | 'task_assigned' | 'task_progress' | 'task_completed' | 'task_failed' | 'summary' | 'done' | 'error'
  plan?: TaskPlan
  subtask?: SubTask
  subtaskId?: string
  agentId?: string
  agentName?: string
  progress?: string
  result?: string
  summary?: string
  error?: string
  /** The execution was deliberately stopped before the plan finished. */
  cancelled?: boolean
}

export interface GoalConfig {
  goal: string
  maxSteps: number
  timeout: number
  autoAdjust: boolean
}

export interface GoalStep {
  id: string
  index: number
  description: string
  status: TaskStatus
  result?: string
  /** Tool activity produced while this step is executing. */
  toolCalls?: ToolCall[]
  startedAt?: number
  completedAt?: number
}

export interface GoalProgress {
  goal: string
  steps: GoalStep[]
  currentStepIndex: number
  totalSteps: number
  status: TaskStatus
  startedAt: number
  completedAt?: number
  summary?: string
  /** The chat that owns this goal, used to keep progress scoped on conversation switches. */
  conversationId?: string
}

/**
 * A stopped Goal must not retain a visually active step. Pending steps remain
 * pending so a later resume can continue from a truthful checkpoint.
 */
export function markGoalProgressCancelled(progress: GoalProgress, completedAt = Date.now()): GoalProgress {
  return {
    ...progress,
    status: 'cancelled',
    completedAt,
    steps: progress.steps.map((step) => step.status === 'in_progress'
      ? { ...step, status: 'cancelled', completedAt }
      : step),
  }
}

/** Marks an interrupted active step as failed so a failed Goal never renders as still running. */
export function markGoalProgressFailed(progress: GoalProgress, error: string, completedAt = Date.now()): GoalProgress {
  return {
    ...progress,
    status: 'failed',
    completedAt,
    steps: progress.steps.map((step) => step.status === 'in_progress'
      ? { ...step, status: 'failed', result: error, completedAt }
      : step),
  }
}

export interface TaskFeedback {
  id: string
  content: string
  createdAt: number
  checkpointId?: string
}

export interface TaskCheckpoint {
  id: string
  title: string
  description?: string
  status: 'recorded' | 'completed' | 'needs_attention'
  createdAt: number
  stepId?: string
  feedback: TaskFeedback[]
}

export type TaskRunStatus = 'queued' | 'running' | 'paused' | 'completed' | 'failed' | 'cancelled' | 'interrupted'

/** Scheduler metadata retained alongside the execution plan and checkpoints. */
export interface TaskExecutionState {
  state: 'queued' | 'running' | 'retrying' | 'completed' | 'failed' | 'cancelled'
  attempt: number
  maxAttempts: number
  queuedAt: number
  startedAt?: number
  lastActivityAt?: number
  nextRetryAt?: number
}

/** Durable metadata for a checkpointed replay after interruption or failure. */
export interface TaskRecoveryState {
  replayCount: number
  lastReplayAt: number
  reason: 'user-continue' | 'app-restart'
}

export interface TaskRunSnapshot {
  conversationId: string
  kind: 'expert' | 'goal'
  status: TaskRunStatus
  /** Original request data allows queued work to resume after an app restart. */
  goal?: string
  agentId?: string
  execution?: TaskExecutionState
  recovery?: TaskRecoveryState
  plan?: TaskPlan
  progress?: GoalProgress
  summary?: string
  error?: string
  checkpoints?: TaskCheckpoint[]
  updatedAt: number
}

/** A project-level, concise view of one persisted Goal or Team execution. */
export interface TaskArtifactItem {
  id: string
  kind: 'step' | 'source' | 'file' | 'tool'
  title: string
  detail?: string
  status?: TaskStatus
  result?: string
  url?: string
  path?: string
  isError?: boolean
  /** Repeated actions against the same logical target are summarized once. */
  count?: number
}

export interface TaskArtifactRun {
  conversationId: string
  conversationTitle: string
  agentId: string
  workspaceId?: string
  kind: TaskRunSnapshot['kind']
  status: TaskRunSnapshot['status']
  goal: string
  summary?: string
  error?: string
  updatedAt: number
  steps: TaskArtifactItem[]
  sources: TaskArtifactItem[]
  files: TaskArtifactItem[]
  tools: TaskArtifactItem[]
  checkpoints: TaskCheckpoint[]
}
