import type { ToolCall } from './conversation'
import type { AgentModelPreference } from './agent'

export type TaskStatus = 'pending' | 'in_progress' | 'completed' | 'failed' | 'cancelled'

export interface TaskPlan {
  id: string
  goal: string
  subtasks: SubTask[]
  createdAt: number
  status: TaskStatus
  /** Specialists generated by the leader for this plan only. */
  dynamicAgents?: DynamicAgentProfile[]
}

export interface DynamicAgentProfile {
  id: string
  name: string
  description: string
  systemPrompt: string
  tools: string[]
  modelPreference?: AgentModelPreference
}

export interface SubTask {
  id: string
  planId: string
  title: string
  description: string
  status: TaskStatus
  assignedAgentId?: string
  assignedAgentName?: string
  /** Role selected by the leader during planning. */
  assignedRole?: 'researcher' | 'coder' | 'reviewer' | 'tester'
  /** Exact connection chosen for this execution, after model matching. */
  assignedProviderId?: string
  assignedModel?: string
  /** References a task-scoped member from TaskPlan.dynamicAgents. */
  assignedAgentProfileId?: string
  isDynamicAgent?: boolean
  /** Separate persisted context for this agent's work on the subtask. */
  agentConversationId?: string
  /** One-based execution attempt number. Failed tasks are retried once. */
  attempt?: number
  dependencies: string[]
  result?: string
  startedAt?: number
  completedAt?: number
}

export interface TeamEvent {
  type: 'plan_created' | 'task_created' | 'task_assigned' | 'task_progress' | 'task_completed' | 'task_failed' | 'summary' | 'done' | 'error'
  plan?: TaskPlan
  subtask?: SubTask
  subtaskId?: string
  agentId?: string
  agentName?: string
  progress?: string
  result?: string
  summary?: string
  error?: string
}

export interface GoalConfig {
  goal: string
  maxSteps: number
  timeout: number
  autoAdjust: boolean
}

export interface GoalStep {
  id: string
  index: number
  description: string
  status: TaskStatus
  result?: string
  /** Tool activity produced while this step is executing. */
  toolCalls?: ToolCall[]
  startedAt?: number
  completedAt?: number
}

export interface GoalProgress {
  goal: string
  steps: GoalStep[]
  currentStepIndex: number
  totalSteps: number
  status: TaskStatus
  startedAt: number
  completedAt?: number
  summary?: string
  /** The chat that owns this goal, used to keep progress scoped on conversation switches. */
  conversationId?: string
}
